services:
  - type: web
    name: costcontrol-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService: 
          type: web
          name: costcontrol-backend
          property: port 